To image possible dans un environement

diff --git a/imagen b/imagen
--- a/imagen
+++ b/imagen
@@ -1,4 +1,5 @@
 #! /bin/sh
+TMP=/usr/tmp
 LATEX=latex
 DVIPS=dvips
 GS=gs
@@ -34,36 +35,36 @@ ${LATEX} ${BASE}.image.tex
 if ${NEWDVIPS}
 then
   DVIPSOPTS="${DVIPSOPTS} -S 1 -i"
-  ${DVIPS} ${DVIPSOPTS} -o${BASE} ${NAME}.dvi
+  ${DVIPS} ${DVIPSOPTS} -o${TMP}/${BASE} ${NAME}.dvi
   ${RM} ${NAME}.log ${NAME}.aux ${NAME}.dvi
 
-  test -f ${BASE}001 || {  echo "Failure: no ps files!" 2>&1 ; exit 2 ; }
-  for i in ${BASE}[0-9][0-9][0-9]
+  test -f ${TMP}/${BASE}001 || {  echo "Failure: no ps files!" 2>&1 ; exit 2 ; }
+  for i in ${TMP}/${BASE}[0-9][0-9][0-9]
   do
     mv $i $i.ps
     (echo "($i.ps) run" ; echo "quit") |\
     ${GS} ${GSOPTS} -sOutputFile=$i.ppm
     ${PNMCROP} < $i.ppm  |\
     ${PNMMARGIN} ${PNMMARGINOPTS} |\
-    ${PPMTOGIF} ${PPMTOGIFOPTS} > $i.gif
+    ${PPMTOGIF} ${PPMTOGIFOPTS} > `basename $i`.gif
     ${RM} $i.ps $i.ppm
   done
 else
-  ${DVIPS} ${DVIPSOPTS} -o${BASE}.ps ${NAME}.dvi
+  ${DVIPS} ${DVIPSOPTS} -o${TMP}/${BASE}.ps ${NAME}.dvi
   ${RM} ${NAME}.log ${NAME}.aux ${NAME}.dvi
 
-  test -f ${BASE}.ps || { echo "No ps file!" 2>&1 ; exit 2 ; }
+  test -f ${TMP}/${BASE}.ps || { echo "No ps file!" 2>&1 ; exit 2 ; }
 
-  (echo "(${BASE}.ps) run" ; echo "quit") |\
-  ${GS} ${GSOPTS} -sOutputFile=${BASE}%03d
-  ${RM} ${BASE}.ps
+  (echo "(${TMP}/${BASE}.ps) run" ; echo "quit") |\
+  ${GS} ${GSOPTS} -sOutputFile=${TMP}/${BASE}%03d
+  ${RM} ${TMP}/${BASE}.ps
 
-  test -f ${BASE}001 || { echo "No ppm files!"  2>&1 ; exit 2 ; }
-  for i in ${BASE}[0-9][0-9][0-9]
+  test -f ${TMP}/${BASE}001 || { echo "No ppm files!"  2>&1 ; exit 2 ; }
+  for i in ${TMP}/${BASE}[0-9][0-9][0-9]
   do
     ${PNMCROP}  < $i |\
     ${PNMMARGIN} ${PNMMARGINOPTS} |\
-    ${PPMTOGIF} ${PPMTOGIFOPTS}  > $i.gif
+    ${PPMTOGIF} ${PPMTOGIFOPTS}  > `basename $i`.gif
     ${RM} $i
   done
 fi
