Soir avant la release

diff --git a/imagen b/imagen
--- a/imagen
+++ b/imagen
@@ -1,7 +1,6 @@
 #! /bin/sh
 TMPBASE=/usr/tmp
 TMP=${TMPBASE}/imagen$$
-mkdir ${TMP} || { echo "Failure: cannot create tmp dir $TMP" 2>&1 ; exit 2 ; }
 LATEX=latex
 DVIPS=dvips
 GS=gs
@@ -10,6 +9,7 @@ PPMTOGIF=ppmtogif
 PNMMARGIN=pnmmargin
 RM="/bin/rm -f"
 
+trap "/bin/rm -rf ${TMP} ; exit 2" 1 2 3 8 10 13 15
 case $1 in
   '')
    BASE=image
@@ -34,6 +34,8 @@ fi
 test -f  ${NAME}.tex ||\
 { echo "Failure: no ${NAME}.tex file!" 2>&1 ; exit 2 ; }
 ${LATEX} ${BASE}.image.tex
+
+mkdir ${TMP} || { echo "Failure: cannot create tmp dir $TMP" 2>&1 ; exit 2 ; }
 
 if ${NEWDVIPS}
 then
