* Fix quoting bug in recipe for "version.tex". * Indroduce variables for all binaries. * Make phony targets where possible. * Rely in automatic variables in recipes. * Rewrite LaTeX recipe to follow Hevea's `-fix' option.

diff --git a/doc/Makefile b/doc/Makefile
--- a/doc/Makefile
+++ b/doc/Makefile
@@ -1,82 +1,125 @@
-LATEX=latex
-GPIC=gpic
-HEVEA=hevea
-HEVEAOPTS=-fix -exec xxdate.exe -O
-HACHA=hacha
-HACHAOPTS=-tocbis
-IMAGEN=imagen
-HTMLDIR=$(HOME)/public_html/hevea
-DOCDIR=$(HTMLDIR)/doc
-DISTRIDIR=$(HTMLDIR)/distri
+DVIPS = dvips
+DVIPSOPTS = -D 600 -t a4
+GPIC = gpic
+HACHA = hacha
+HACHAOPTS = -tocbis
+HEVEA = hevea
+HEVEAOPTS = -fix -exec xxdate.exe -O
+IMAGEN = imagen
+LATEX = latex
+LATEXOPTS = -file-line-error -interaction nonstopmode -halt-on-error
+MAKEINDEX = makeindex
+MAKEINDEXOPTS =
+PS2PDF = ps2pdf
+PS2PDFOPTS =
 
+HTMLDIR = $(HOME)/public_html/hevea
+DISTRIDIR = $(HTMLDIR)/distri
+DOCDIR = $(HTMLDIR)/doc
+
+
+.PHONY: all
 all: doc doc/index.html thai
+
+.PHONY: dvi
+dvi: manual.dvi
+
+.PHONY: html
 html: doc/index.html
 
-doc:
-	mkdir -p doc
-	cp fddl.html doc
+.PHONY: info
+info: manual.info
 
+.PHONY: pdf
+pdf: manual.pdf
+
+.PHONY: ps
+ps: manual.ps
+
+.PHONY: text
+text: manual.txt
+
+
+doc:
+	mkdir -p $@
+	cp fddl.html $@
+
+.PHONY: docclean
 docclean::
-	/bin/rm -f doc/manual.h{tml,aux,ind,toc} doc/manual.image.tex
+	$(RM) ./doc/manual.h{tml,aux,ind,toc} ./doc/manual.image.tex
 
 opt:
-	export HEVEADIR=.. ;\
-	$(MAKE) $(MFLAGS) HEVEAOPTS="$(HEVEAOPTS)" HACHAOPTS="$(HACHAOPTS)" HEVEA=../hevea.opt HACHA=../hacha.opt IMAGEN=../imagen all
+	HEVEADIR=.. $(MAKE) $(MFLAGS) HEVEAOPTS="$(HEVEAOPTS)" HACHAOPTS="$(HACHAOPTS)" HEVEA=../hevea.opt HACHA=../hacha.opt IMAGEN=../imagen all
 
 infoopt:
-	export HEVEADIR=.. ;\
-	$(MAKE) $(MFLAGS) HEVEAOPTS="$(HEVEAOPTS)" HACHAOPTS="$(HACHAOPTS)" HEVEA=../hevea.opt HACHA=../hacha.opt IMAGEN=imagen.opt info
+	HEVEADIR=.. $(MAKE) $(MFLAGS) HEVEAOPTS="$(HEVEAOPTS)" HACHAOPTS="$(HACHAOPTS)" HEVEA=../hevea.opt HACHA=../hacha.opt IMAGEN=imagen.opt info
 
 byte:
-	export HEVEADIR=.. ;\
-	$(MAKE) $(MFLAGS) HEVEAOPTS="$(HEVEAOPTS)" HACHAOPTS="$(HACHAOPTS)" HEVEA="../hevea.byte" HACHA=../hacha.byte IMAGEN=../imagen all
+	HEVEADIR=.. $(MAKE) $(MFLAGS) HEVEAOPTS="$(HEVEAOPTS)" HACHAOPTS="$(HACHAOPTS)" HEVEA=../hevea.byte HACHA=../hacha.byte IMAGEN=../imagen all
 
 tmp.tex: text.tex
-	$(GPIC) -t < text.tex > tmp.tex
+	$(GPIC) -t < $< > $@
 
-doc/manual.html: doc manual.hva  macros.tex manual.tex version.tex tmp.tex
-	$(HEVEA) $(HEVEAOPTS) -o doc/manual.html manual.hva manual.tex
+MANUAL_DEPENDENCIES = manual.tex macros.tex tmp.tex version.tex # "manual.tex" MUST be first!
 
-manual.dvi: manual.tex macros.tex version.tex tmp.tex
-	$(LATEX) < /dev/null manual.tex &&\
-	$(LATEX) < /dev/null manual.tex &&\
-	makeindex manual.idx &&\
-	$(LATEX) < /dev/null manual.tex
-
-manual.ps: manual.dvi
-	dvips -o manual.ps manual.dvi
-
-manual.pdf: manual.ps
-	ps2pdf manual.ps
+doc/manual.html: doc manual.hva $(MANUAL_DEPENDENCIES)
+	$(HEVEA) $(HEVEAOPTS) -o $@ manual.hva manual.tex
 
 doc/index.html: doc/manual.html
-	$(HACHA) $(HACHAOPTS) -o doc/index.html doc/manual.html
+	$(HACHA) $(HACHAOPTS) -o $@ $<
 
-info: manual.inf tmp.tex
-	$(HEVEA) $(HEVEAOPTS) -info manual.inf manual.tex -o manual.info
+manual.dvi: $(MANUAL_DEPENDENCIES)
+	$(LATEX) $(LATEXOPTS) $<
+	$(MAKEINDEX) $(MAKEINDEXOPTS) $*.idx
+	$(LATEX) $(LATEXOPTS) $<
+	@ITER=2; MAXITER=10;  \
+        while test -e $*.log && grep -q 'LaTeX Warning: Label(s) may have changed' $*.log; do  \
+            test $$ITER -le $$MAXITER || { printf 'Excessive number of iterations (%d) to reach fixpoint.  Aborted!\n' "$$MAXITER" 1>&2; exit 1; };  \
+            printf 'Run LaTeX again.\n'  \
+            $(LATEX) $(LATEXOPTS) $< > /dev/null 2>&1;  \
+            : $$((ITER += 1));  \
+	done;  \
+        printf 'Fixpoint reached after %d iteration(s).\n' "$$ITER"
 
-thai: doc doc/thaihevea.html
+manual.ps: manual.dvi
+	$(DVIPS) $(DVIPSOPTS) -o $@ $<
 
-doc/thaihevea.html: thai/thaihevea.ttex
-	export TEXINPUTS="thai:" ; $(HEVEA)  $(HEVEAOPTS) -o $@ $<
+manual.pdf: manual.ps
+	$(PS2PDF) $(PS2PDFOPTS) $<
+
+manual.info: $(MANUAL_DEPENDENCIES)
+	$(HEVEA) $(HEVEAOPTS) -info -o $@ $<
+
+manual.txt: $(MANUAL_DEPENDENCIES)
+	$(HEVEA) $(HEVEAOPTS) -text -o $@ $<
+
+.PHONY: thai
+thai: doc/thaihevea.html
+
+doc/thaihevea.html: doc thai/thaihevea.ttex
+	TEXINPUTS="thai:" $(HEVEA) $(HEVEAOPTS) -o $@ $<
 
 docclean::
-	/bin/rm -f doc/thaihevea.h{aux,ind,toc} doc/thaihevea.image.tex
+	$(RM) doc/thaihevea.h{aux,ind,toc} doc/thaihevea.image.tex
 
 ############# Release stuff
 VERSIONFILE=../version.ml
 
 version.tex: $(VERSIONFILE)
-	sed -n -e 's/^let real_version = "\(.*\)".*$$/\\def\\heveaversion{\1}/p' $(VERSIONFILE) > version.tex
-	sed -n -e 's/^let release_date = "\([0-9\-]*\)".*$$/\\def\\releasedate{\1}/p' $(VERSIONFILE) >> version.tex
-	echo '\\newif\\ifdevrelease\\devreleasefalse' >> version.tex
-	sed -n -e '/let real_version = ".*+.*"/s//\\devreleasetrue/p' $(VERSIONFILE) >> version.tex
+	printf '%%%%%%  Automatically generated by doc/Makefile.\n' > $@
+	sed -n -e 's/^let real_version = "\(.*\)".*$$/\\def\\heveaversion{\1}/p' < $(VERSIONFILE) >> $@
+	sed -n -e 's/^let release_date = "\([0-9\-]*\)".*$$/\\def\\releasedate{\1}/p' < $(VERSIONFILE) >> $@
+	printf '\\newif\\ifdevrelease\\devreleasefalse\n' >> $@
+	sed -n -e '/let real_version = ".*+.*"/s//\\devreleasetrue/p' < $(VERSIONFILE) >> $@
 
+
+.PHONY: clean
 clean:
-	rm -f *~ *.aux *.log *.toc *.idx *.ilg *.ind *.haux *.hidx *.hind *.htoc *.hrf
+	$(RM) ./*.aux ./*.idx ./*.ilg ./*.ind ./*.log ./*.toc
+	$(RM) ./*.haux ./*.hidx ./*.hind ./*.hrf ./*.htoc
 
+.PHONY: cleanall
 cleanall: clean
-	rm -f manual.dvi manual.ps manual.pdf
-	rm -f faq.html hevea.spec manual.txt manual.info manual.info-[0-9] pdfmanual.pdf
-	/bin/rm -rf doc
-	/bin/rm -f tmp.tex version.tex
+	$(RM) manual.{dvi,pdf,ps,txt} manual.info manual.info-[0-9]
+	$(RM) faq.html hevea.spec pdfmanual.pdf tmp.tex version.tex
+	$(RM) -r doc
